apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-deployment
  labels:
    app: oracle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
        - name: oracle-container
          image: your-docker-repo/oracle-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: CHAIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: oracle-config
                  key: chainName
            - name: STACKS_RPC_URL
              valueFrom:
                configMapKeyRef:
                  name: oracle-config
                  key: rpcUrl
            - name: STACKS_CONTRACT
              valueFrom:
                configMapKeyRef:
                  name: oracle-config
                  key: contract
            - name: STACKS_CONTRACT_NAME
              valueFrom:
                configMapKeyRef:
                  name: oracle-config
                  key: contractName
            - name: STACKS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: oracle-secrets
                  key: secretKey
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
