/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
} from "@alephium/web3";
import { default as DIAOracleValueContractJson } from "../oracle/DIAOracleValue.ral.json";
import { getContractByCodeHash } from "./contracts";
import { Random, AllStructs } from "./types";

// Custom types for the contract
export namespace DIAOracleValueTypes {
  export type Fields = {
    oracle: HexString;
    value: bigint;
    timestamp: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getValue: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTimestamp: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  DIAOracleValueInstance,
  DIAOracleValueTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as DIAOracleValueTypes.Fields;
  }

  consts = { InvalidCaller: BigInt(0) };

  at(address: string): DIAOracleValueInstance {
    return new DIAOracleValueInstance(address);
  }

  tests = {
    getValue: async (
      params: Omit<
        TestContractParamsWithoutMaps<DIAOracleValueTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getValue", params);
    },
    getTimestamp: async (
      params: Omit<
        TestContractParamsWithoutMaps<DIAOracleValueTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTimestamp", params);
    },
    update: async (
      params: TestContractParamsWithoutMaps<
        DIAOracleValueTypes.Fields,
        { newValue: bigint; newTimestamp: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "update", params);
    },
  };
}

// Use this object to test and deploy the contract
export const DIAOracleValue = new Factory(
  Contract.fromJson(
    DIAOracleValueContractJson,
    "",
    "49b08abbeec80d6cc22c0320602da0558b8e9effba33c4bbc7cb82a73934f4bf",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class DIAOracleValueInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DIAOracleValueTypes.State> {
    return fetchContractState(DIAOracleValue, this);
  }

  methods = {
    getValue: async (
      params?: DIAOracleValueTypes.CallMethodParams<"getValue">
    ): Promise<DIAOracleValueTypes.CallMethodResult<"getValue">> => {
      return callMethod(
        DIAOracleValue,
        this,
        "getValue",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTimestamp: async (
      params?: DIAOracleValueTypes.CallMethodParams<"getTimestamp">
    ): Promise<DIAOracleValueTypes.CallMethodResult<"getTimestamp">> => {
      return callMethod(
        DIAOracleValue,
        this,
        "getTimestamp",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends DIAOracleValueTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DIAOracleValueTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      DIAOracleValue,
      this,
      calls,
      getContractByCodeHash
    )) as DIAOracleValueTypes.MultiCallResults<Calls>;
  }
}
