/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { RunScriptResult, DeployContractExecutionResult } from "@alephium/cli";
import { NetworkId } from "@alephium/web3";
import {
  DIAOracleValue,
  DIAOracleValueInstance,
  DIAOracle,
  DIAOracleInstance,
  DIARandomValue,
  DIARandomValueInstance,
  DIARandomOracle,
  DIARandomOracleInstance,
} from ".";
import { default as devnetDeployments } from "../.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    DIAOracleValue: DeployContractExecutionResult<DIAOracleValueInstance>;
    DIAOracle: DeployContractExecutionResult<DIAOracleInstance>;
    DIARandomValue: DeployContractExecutionResult<DIARandomValueInstance>;
    DIARandomOracle: DeployContractExecutionResult<DIARandomOracleInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    DIAOracleValue: {
      ...json.contracts["DIAOracleValue"],
      contractInstance: DIAOracleValue.at(
        json.contracts["DIAOracleValue"].contractInstance.address
      ),
    },
    DIAOracle: {
      ...json.contracts["DIAOracle"],
      contractInstance: DIAOracle.at(
        json.contracts["DIAOracle"].contractInstance.address
      ),
    },
    DIARandomValue: {
      ...json.contracts["DIARandomValue"],
      contractInstance: DIARandomValue.at(
        json.contracts["DIARandomValue"].contractInstance.address
      ),
    },
    DIARandomOracle: {
      ...json.contracts["DIARandomOracle"],
      contractInstance: DIARandomOracle.at(
        json.contracts["DIARandomOracle"].contractInstance.address
      ),
    },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments = networkId === "devnet" ? devnetDeployments : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
