/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
} from "@alephium/web3";
import { default as DIAOracleContractJson } from "../oracle/DIAOracle.ral.json";
import { getContractByCodeHash } from "./contracts";
import { Random, AllStructs } from "./types";

// Custom types for the contract
export namespace DIAOracleTypes {
  export type Fields = {
    oracleValueTemplateId: HexString;
    admin: Address;
    subContractDeposit: bigint;
  };

  export type State = ContractState<Fields>;

  export type AdminChangedEvent = ContractEvent<{ newAdmin: Address }>;
  export type OracleUpdateEvent = ContractEvent<{
    key: HexString;
    value: bigint;
    timestamp: bigint;
  }>;

  export interface CallMethodTable {
    getAdmin: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getSubContractDeposit: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getValue: {
      params: CallContractParams<{ key: HexString }>;
      result: CallContractResult<[bigint, bigint]>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  DIAOracleInstance,
  DIAOracleTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as DIAOracleTypes.Fields;
  }

  eventIndex = { AdminChanged: 0, OracleUpdate: 1 };
  consts = {
    MaxBatchSize: BigInt(10),
    ErrorCodes: { AdminAllowedOnly: BigInt(0), InvalidBatchSize: BigInt(1) },
  };

  at(address: string): DIAOracleInstance {
    return new DIAOracleInstance(address);
  }

  tests = {
    getAdmin: async (
      params: Omit<
        TestContractParamsWithoutMaps<DIAOracleTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getAdmin", params);
    },
    getSubContractDeposit: async (
      params: Omit<
        TestContractParamsWithoutMaps<DIAOracleTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getSubContractDeposit", params);
    },
    changeAdmin: async (
      params: TestContractParamsWithoutMaps<
        DIAOracleTypes.Fields,
        { newAdmin: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "changeAdmin", params);
    },
    setSubContractDeposit: async (
      params: TestContractParamsWithoutMaps<
        DIAOracleTypes.Fields,
        { value: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setSubContractDeposit", params);
    },
    checkAdmin: async (
      params: TestContractParamsWithoutMaps<
        DIAOracleTypes.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "checkAdmin", params);
    },
    getValue: async (
      params: TestContractParamsWithoutMaps<
        DIAOracleTypes.Fields,
        { key: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<[bigint, bigint]>> => {
      return testMethod(this, "getValue", params);
    },
    setValue: async (
      params: TestContractParamsWithoutMaps<
        DIAOracleTypes.Fields,
        { key: HexString; value: bigint; timestamp: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setValue", params);
    },
    setMultipleValues: async (
      params: TestContractParamsWithoutMaps<
        DIAOracleTypes.Fields,
        {
          keys: [
            HexString,
            HexString,
            HexString,
            HexString,
            HexString,
            HexString,
            HexString,
            HexString,
            HexString,
            HexString
          ];
          values: [
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint
          ];
          timestamps: [
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint,
            bigint
          ];
          batchSize: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setMultipleValues", params);
    },
    updateValue: async (
      params: TestContractParamsWithoutMaps<
        DIAOracleTypes.Fields,
        { key: HexString; value: bigint; timestamp: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateValue", params);
    },
  };
}

// Use this object to test and deploy the contract
export const DIAOracle = new Factory(
  Contract.fromJson(
    DIAOracleContractJson,
    "",
    "ad57e1ace4e9e9646efee86597a76c477d6cde0c31a796f1c7d4acfd2a2c5113",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class DIAOracleInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DIAOracleTypes.State> {
    return fetchContractState(DIAOracle, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeAdminChangedEvent(
    options: EventSubscribeOptions<DIAOracleTypes.AdminChangedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      DIAOracle.contract,
      this,
      options,
      "AdminChanged",
      fromCount
    );
  }

  subscribeOracleUpdateEvent(
    options: EventSubscribeOptions<DIAOracleTypes.OracleUpdateEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      DIAOracle.contract,
      this,
      options,
      "OracleUpdate",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      DIAOracleTypes.AdminChangedEvent | DIAOracleTypes.OracleUpdateEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      DIAOracle.contract,
      this,
      options,
      fromCount
    );
  }

  methods = {
    getAdmin: async (
      params?: DIAOracleTypes.CallMethodParams<"getAdmin">
    ): Promise<DIAOracleTypes.CallMethodResult<"getAdmin">> => {
      return callMethod(
        DIAOracle,
        this,
        "getAdmin",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSubContractDeposit: async (
      params?: DIAOracleTypes.CallMethodParams<"getSubContractDeposit">
    ): Promise<DIAOracleTypes.CallMethodResult<"getSubContractDeposit">> => {
      return callMethod(
        DIAOracle,
        this,
        "getSubContractDeposit",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getValue: async (
      params: DIAOracleTypes.CallMethodParams<"getValue">
    ): Promise<DIAOracleTypes.CallMethodResult<"getValue">> => {
      return callMethod(
        DIAOracle,
        this,
        "getValue",
        params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends DIAOracleTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DIAOracleTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      DIAOracle,
      this,
      calls,
      getContractByCodeHash
    )) as DIAOracleTypes.MultiCallResults<Calls>;
  }
}
