/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
} from "@alephium/web3";
import { default as DIARandomOracleContractJson } from "../random/DIARandomOracle.ral.json";
import { getContractByCodeHash } from "./contracts";
import { Random, AllStructs } from "./types";

// Custom types for the contract
export namespace DIARandomOracleTypes {
  export type Fields = {
    randomValueTemplateId: HexString;
    admin: Address;
    subContractDeposit: bigint;
    lastRound: bigint;
  };

  export type State = ContractState<Fields>;

  export type AdminChangedEvent = ContractEvent<{ newAdmin: Address }>;
  export type OracleUpdateEvent = ContractEvent<{
    round: bigint;
    randomness: HexString;
    signature: HexString;
    previousSignature: HexString;
  }>;

  export interface CallMethodTable {
    getAdmin: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getSubContractDeposit: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getLastRound: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getRandomValue: {
      params: CallContractParams<{ round: bigint }>;
      result: CallContractResult<Random>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  DIARandomOracleInstance,
  DIARandomOracleTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as DIARandomOracleTypes.Fields;
  }

  eventIndex = { AdminChanged: 0, OracleUpdate: 1 };
  consts = {
    ErrorCodes: { AdminAllowedOnly: BigInt(0), InvalidRound: BigInt(1) },
  };

  at(address: string): DIARandomOracleInstance {
    return new DIARandomOracleInstance(address);
  }

  tests = {
    getAdmin: async (
      params: Omit<
        TestContractParamsWithoutMaps<DIARandomOracleTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getAdmin", params);
    },
    getSubContractDeposit: async (
      params: Omit<
        TestContractParamsWithoutMaps<DIARandomOracleTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getSubContractDeposit", params);
    },
    changeAdmin: async (
      params: TestContractParamsWithoutMaps<
        DIARandomOracleTypes.Fields,
        { newAdmin: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "changeAdmin", params);
    },
    setSubContractDeposit: async (
      params: TestContractParamsWithoutMaps<
        DIARandomOracleTypes.Fields,
        { value: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setSubContractDeposit", params);
    },
    checkAdmin: async (
      params: TestContractParamsWithoutMaps<
        DIARandomOracleTypes.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "checkAdmin", params);
    },
    getLastRound: async (
      params: Omit<
        TestContractParamsWithoutMaps<DIARandomOracleTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getLastRound", params);
    },
    getRandomValue: async (
      params: TestContractParamsWithoutMaps<
        DIARandomOracleTypes.Fields,
        { round: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<Random>> => {
      return testMethod(this, "getRandomValue", params);
    },
    setRandomValue: async (
      params: TestContractParamsWithoutMaps<
        DIARandomOracleTypes.Fields,
        { round: bigint; value: Random }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setRandomValue", params);
    },
  };
}

// Use this object to test and deploy the contract
export const DIARandomOracle = new Factory(
  Contract.fromJson(
    DIARandomOracleContractJson,
    "",
    "aa03cc1c493574b8791003ae68adc838432002955dce2252d428c2de3981cbc7",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class DIARandomOracleInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DIARandomOracleTypes.State> {
    return fetchContractState(DIARandomOracle, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeAdminChangedEvent(
    options: EventSubscribeOptions<DIARandomOracleTypes.AdminChangedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      DIARandomOracle.contract,
      this,
      options,
      "AdminChanged",
      fromCount
    );
  }

  subscribeOracleUpdateEvent(
    options: EventSubscribeOptions<DIARandomOracleTypes.OracleUpdateEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      DIARandomOracle.contract,
      this,
      options,
      "OracleUpdate",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | DIARandomOracleTypes.AdminChangedEvent
      | DIARandomOracleTypes.OracleUpdateEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      DIARandomOracle.contract,
      this,
      options,
      fromCount
    );
  }

  methods = {
    getAdmin: async (
      params?: DIARandomOracleTypes.CallMethodParams<"getAdmin">
    ): Promise<DIARandomOracleTypes.CallMethodResult<"getAdmin">> => {
      return callMethod(
        DIARandomOracle,
        this,
        "getAdmin",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSubContractDeposit: async (
      params?: DIARandomOracleTypes.CallMethodParams<"getSubContractDeposit">
    ): Promise<
      DIARandomOracleTypes.CallMethodResult<"getSubContractDeposit">
    > => {
      return callMethod(
        DIARandomOracle,
        this,
        "getSubContractDeposit",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getLastRound: async (
      params?: DIARandomOracleTypes.CallMethodParams<"getLastRound">
    ): Promise<DIARandomOracleTypes.CallMethodResult<"getLastRound">> => {
      return callMethod(
        DIARandomOracle,
        this,
        "getLastRound",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getRandomValue: async (
      params: DIARandomOracleTypes.CallMethodParams<"getRandomValue">
    ): Promise<DIARandomOracleTypes.CallMethodResult<"getRandomValue">> => {
      return callMethod(
        DIARandomOracle,
        this,
        "getRandomValue",
        params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends DIARandomOracleTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DIARandomOracleTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      DIARandomOracle,
      this,
      calls,
      getContractByCodeHash
    )) as DIARandomOracleTypes.MultiCallResults<Calls>;
  }
}
